### ISSUE TITLE
Criar um arquivo de configurações

### ISSUE THREAD

**Issue by mocno** [mocno/bandex#12]
Como citado nos issues #1 e #6, esse projeto precisa de arquivo de configurações para algumas funcionalidades importantes, como principais restaurantes e favoritos ou a listas de comidas gostadas e não gostadas. Desse contexto, é necessário pensar em alguns pontos para esse arquivo de configuração: que extensão e formatação esse arquivo usará, quais serão os parâmetros configuráveis e onde esse arquivo ficará.
Para o primeiro ponto, que extensão e formatação esse arquivo usará, as principais opções são:
- [x] `yaml` - o melhor candidato, pois é feito para ser humanamente legível e é feito para arquivos de configurações, como este. E é facilmente escrito em um bloco de notas, por exemplo.
- [ ] `json` - um dos melhores candidatos, apesar de não ser o principal tipo de arquivo para configuração, perdendo nesse ponto para o `yaml`, e normalmente usado para guardar e trocar de dados, ele permite uma fácil edição e leitura.
- [ ] `toml` - com vantagens parecidas do `yaml`, mas ainda mais simples - isso pode ser um bom motivo para a sua escolha, por outro lado, é menos conhecida que o `yaml`.
- [ ] `xml` - sinceramente só coloquei ele por respeito aos mais velhos (apesar de ter uma idade parecida com a maioria dos seus concorrentes), ele tem pouco legibilidade e é difícil de editar.

Para o segundo ponto, os parâmetros configuráveis, os dois issues levantam possibilidades de alguns desses parâmetros:
- Parâmentros dos restaurantes:
  - `selected-restaurants-ids` - os IDs dos restaurantes que deseja-se aparecer por padrão.
  - `restaurants-colors` - adicionar cor por restaurante.
- Parâmentros do cardápio:
  - `liked-foods` e `disliked-foods` - para a lista de comidas gostadas e não gostadas.

Por fim, o terceiro ponto pode ser pensado em outra hora, pois, em primeiro momento, esse arquivo de configurações deve ser carregado por um argumento `--config-file` no CLI.

**Comment by mocno** [comment]
Caso o arquivo de configurações seja, de fato, yaml, o arquivo de configurações pode ser do formato:
```yaml
# Configurações do Bandex
bandex:
  restaurants:
    - # Restaurante Física
      id: &RESTAURANT_FISICA 8
      color: red

    - # Restaurante Química
      id: &RESTAURANT_QUIMICA 9
      color: blue

    - # Restaurante Prefeitura
      id: &RESTAURANT_PREFEITURA 7
      color: green

    - # Restaurante Central
      id: &RESTAURANT_CENTRAL 6
      color: yellow

  foods:
    # Comidas gostadas
    # - brigadeiro e pudim
    # - barra de cereais (só é gostada no central)
    liked:
      - brigadeiro
      - pudim
      - barra de cereais: [*RESTAURANT_CENTRAL]

    # Comidas não gostadas
    # - acelga
    # - pvt (só não é gostada na física e na prefeitura)
    disliked:
      - pvt: [*RESTAURANT_FISICA, *RESTAURANT_PREFEITURA]
      - acelga
 ```
